(() => {
  'use strict';
  let context, container, opened=false;
  const fmt=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=d=>d?d.split('-').reverse().join('/'):'Não definido';
  const labels={needs_setup:'Configure a data inicial e o saldo real para calcular a meta.',needs_regularization:'Defina os prazos das pendências vencidas para concluir a meta.',no_working_days:'Há contas sem dias disponíveis antes do prazo. Revise os descansos ou negocie o prazo.',cash_inconsistent:'O caixa ficou negativo. Confira recebimentos, pagamentos e saldo inicial.',past:'Mês encerrado. Consulte as metas registradas na tabela diária.',ready:''};
  const base=()=>context.admin?`/api/admin/clients/${context.clientId}`:'/api/finance';
  async function save(kind,body,button){const target=base();button.disabled=true;const msg=container.querySelector('.meta-feedback');msg.textContent='Salvando...';try{const r=await fetch(`${target}/goal-${kind}`,{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível salvar.');const month=context.plan.month;const url=context.admin?`${target}/summary?month=${month}`:`${target}/summary?month=${month}`;const response=await fetch(url,{credentials:'same-origin'});if(!response.ok)throw new Error('Salvo. Atualize a página para carregar o cálculo.');const updated=await response.json();document.dispatchEvent(new CustomEvent('rota-goal-reload',{detail:updated}));}catch(e){msg.textContent=e.message;button.disabled=false;}}
  function breakdown(p){return `<div class="meta-mini-grid"><div><span>Obrigações consideradas</span><strong>${fmt(p.pendingTotal)}</strong></div><div><span>Dinheiro disponível</span><strong>${fmt(p.availableBalance)}</strong></div><div><span>Falta produzir</span><strong>${fmt(p.remainingTotal)}</strong></div><div><span>Dias disponíveis</span><strong>${p.availableWorkingDays}</strong></div></div>
  <p class="meta-caption">Caixa: saldo inicial ${fmt(p.initialBalance)} + recebimentos ${fmt(p.received)} − pagamentos ${fmt(p.paid)} = ${fmt(p.cashBalance)}.</p>
  <div class="meta-scroll"><table class="meta-table"><thead><tr><th>Obrigação</th><th>Vencimento</th><th>Prazo na meta</th><th>Pendente</th><th>Caixa destinado</th><th>Falta produzir</th></tr></thead><tbody>${p.debts.map(d=>`<tr><td>${esc(d.name)}${d.reason?`<small>${esc(d.reason)}</small>`:''}</td><td>${date(d.dueDate)}</td><td>${date(d.deadline)}</td><td>${fmt(d.amount)}</td><td>${fmt(d.cashAllocated)}</td><td>${fmt(d.remaining)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma obrigação pendente nesta janela.</td></tr>'}</tbody></table></div>
  <h3>Verificação por prazo</h3><div class="meta-scroll"><table class="meta-table"><thead><tr><th>Até a data</th><th>Falta produzir acumulado</th><th>Dias disponíveis</th><th>Necessidade diária</th></tr></thead><tbody>${p.checks.map(c=>`<tr><td>${date(c.deadline)}</td><td>${fmt(c.remaining)}</td><td>${c.days}</td><td>${c.blocked?'Sem dias disponíveis':fmt(c.dailyGoal)}${c.dailyGoal===p.dailyGoal&&!c.blocked?' · define a meta':''}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum prazo calculável.</td></tr>'}</tbody></table></div><p class="meta-caption">O caixa é aplicado uma única vez, por ordem de prazo. A maior necessidade diária atende aos vencimentos. Despesas após o mês, fora da meta: ${fmt(p.excludedFutureTotal)}.</p>`;}
  function render(c){if(!c?.plan)return;context=c;const p=c.plan;
    if(!container){container=document.createElement('section');container.id='metaMensalPanel';container.className='meta-panel';const host=c.admin?document.getElementById('clientDetail'):document.querySelector('.planning-container');if(!host)return;const anchor=host.querySelector('.chart-card');host.insertBefore(container,anchor||null);}
    container.innerHTML=`<div class="meta-heading"><div><span class="meta-eyebrow">PLANEJAMENTO MENSAL · ${esc(p.month)}</span><h2>Meta diária para os compromissos do mês</h2></div><button type="button" class="meta-button" id="metaToggle" aria-expanded="${opened}">Ver composição</button></div>
    <div class="meta-mini-grid"><div><span>${c.admin?'Mesma meta do cliente':'Meta recomendada'}</span><strong class="meta-gold">${p.displayDailyGoal==null?'Revisar planejamento':fmt(p.displayDailyGoal)}</strong></div><div><span>Falta produzir</span><strong>${fmt(p.remainingTotal)}</strong></div><div><span>Caixa disponível</span><strong>${fmt(p.availableBalance)}</strong></div><div><span>Dias disponíveis</span><strong>${p.availableWorkingDays}</strong></div></div>
    ${p.status!=='ready'?`<p class="meta-warning" role="status">${esc(labels[p.status])}</p>`:''}
    <div id="metaComposition" ${opened?'':'hidden'}>${breakdown(p)}</div>
    <details ${p.status==='needs_setup'?'open':''}><summary>Data inicial e saldo real do planejamento</summary><p class="meta-caption">Informe o dinheiro que havia disponível no início dessa data, antes das entradas e saídas do dia. O histórico anterior fica preservado. Dívidas antigas ainda não pagas continuam pendentes.</p><form id="metaSettings"><label>Início do planejamento<input type="date" name="start_date" required max="${p.referenceDate}" value="${p.settings?.start_date||p.referenceDate}"></label><label>Saldo disponível no início (R$)<input type="number" name="initial_balance" min="0" step="0.01" required value="${p.initialBalance}"></label><button class="meta-button" type="submit">Salvar base do planejamento</button></form></details>
    ${p.debts.some(d=>d.overdue)?`<details ${p.status==='needs_regularization'?'open':''}><summary>Prazos das despesas vencidas</summary>${p.debts.filter(d=>d.overdue).map(d=>`<form class="meta-regularize" data-entry="${Number(d.id)}"><div><strong>${esc(d.name)} · ${fmt(d.amount)}</strong><p class="meta-caption">Vencimento original: ${date(d.dueDate)}</p></div><label>Regularizar até<input type="date" name="regularize_date" min="${p.referenceDate}" value="${d.deadline||''}" required></label><button class="meta-button" type="submit">Salvar prazo</button></form>`).join('')}</details>`:''}
    <p class="meta-feedback" role="status" aria-live="polite"></p><p class="meta-caption">Referência: ${date(p.referenceDate)} · hoje incluído quando disponível · sábados e domingos contam, exceto descansos cadastrados.</p>`;
    container.querySelector('#metaToggle').onclick=e=>{opened=!opened;container.querySelector('#metaComposition').hidden=!opened;e.target.setAttribute('aria-expanded',String(opened));};
    const form=container.querySelector('#metaSettings');form.onsubmit=e=>{e.preventDefault();save('settings',{start_date:form.elements.start_date.value,initial_balance:form.elements.initial_balance.value},form.querySelector('button'));};
    container.querySelectorAll('.meta-regularize').forEach(f=>f.onsubmit=e=>{e.preventDefault();save('regularization',{entry_id:Number(f.dataset.entry),regularize_date:f.elements.regularize_date.value},f.querySelector('button'));});
    const goal=document.getElementById(c.admin?'detailGoal':'dailyGoal');if(goal){const card=goal.closest('article');let button=card?.querySelector('.meta-card-link');if(card&&!button){button=document.createElement('button');button.type='button';button.className='meta-card-link';button.textContent='Detalhar meta diária';card.appendChild(button);}if(button)button.onclick=()=>{opened=true;container.querySelector('#metaComposition').hidden=false;container.querySelector('#metaToggle').setAttribute('aria-expanded','true');container.scrollIntoView({behavior:'smooth',block:'start'});};}
  }
  document.addEventListener('rota-goal',e=>render(e.detail));
  document.addEventListener('click',e=>{const button=e.target.closest('[data-goal-date]');if(!button||!context)return;const d=button.dataset.goalDate,p=context.plan;const h=p.history.find(x=>x.date===d);const dialog=document.createElement('dialog');dialog.className='meta-dialog';dialog.innerHTML=`<button type="button" class="meta-button" data-close>Fechar</button><h2>Meta de ${date(d)}</h2>${h?`<p>Meta registrada: ${h.dailyGoal==null?'Revisar planejamento':fmt(h.dailyGoal)}</p>${breakdown(h.recorded)}${h.revised?`<h3>Revisão com os lançamentos atuais</h3><p>${h.revised.displayDailyGoal==null?'Revisar planejamento':fmt(h.revised.displayDailyGoal)}</p><p class="meta-caption">O registro original permanece preservado. A revisão usa as datas efetivas dos lançamentos atuais.</p>${breakdown(h.revised)}`:''}`:`<p>Meta ${d===p.referenceDate?'atual':'projetada'}: ${fmt(p.daily.find(x=>x.date===d)?.dailyGoal??0)}</p><p class="meta-caption">Plano com as obrigações conhecidas hoje. Atingir a meta é uma hipótese do planejamento, não um recebimento registrado. Novas movimentações recalculam o futuro.</p>${breakdown(p)}`}`;document.body.appendChild(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();});
  if(window.rotaGoalContext)render(window.rotaGoalContext);
})();
